#! /bin/sh

#auto start
sxhkd &
#compton >/dev/null 2>&1 &
urxvtd &
xfce4-volumed-pulse 
thunar --daemon &
ibus-daemon &
~/.fehbg
runonce redshift
/usr/lib/polkit-gnome/gtkpolkit &

bspc config border_width         2
bspc config window_gap          10

bspc config focused_border_color '#1E88E4'
bspc config normal_border_color  '#555555'

bspc config split_ratio          0.58
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI VII VIII IX X

#rules
bspc rule -a google-chrome desktop=^3 state=fullscreen
bspc rule -a Smplayer2 state=floating
bspc rule -a Thunar state=floating
bspc rule -a feh state=floating
bspc rule -a Engrampa state=floating
bspc rule -a Audacious state=floating
bspc rule -a Arandr state=floating
bspc rule -a Textadept state=floating
bspc rule -a Telegram state=floating
